### ISSUE TITLE
内部互助没生效

### ISSUE THREAD

**Issue by ghost** [hajiuhajiu/jdsign1112#20]
获取互助码完成了，但是没有进行互助，想问问这个问题应该怎么解决？

**Comment by three-body2** [comment]
互助码怎么得，总是Failed to add secret. Name is invalid

**Comment by PMYuYu** [comment]
> 互助码怎么得，总是Failed to add secret. Name is invalid

有个js脚本就是获取内部互助码的，你可以去action看看日志

**Comment by three-body2** [comment]
找到了那个获取互助码的脚本，但互助码在哪找不到啊大佬
