### ISSUE TITLE
web控制面板打不开, 换了两台云服务器了

### ISSUE THREAD

**Issue by cccy0** [hajiuhajiu/jdsign1112#28]
![image](https://user-images.githubusercontent.com/29329157/132374172-364ce8e4-50b6-41a7-a591-3164f1662305.png)

**Comment by hajiuhajiu** [comment]
更新一下就行了，或者重新下载docker镜像安装一遍，之前jd.sh版本问题

运行
bash git_pull.sh
由于github不稳定， 可能一次不一定成功，
