### ISSUE TITLE
使用一段时间之后很多任务不执行（或者可能是执行了没结果）是什么问题呢，要如何解决？

### ISSUE THREAD

**Issue by yiyiyiyayaya123123** [hajiuhajiu/jdsign1112#35]

**Comment by yiyiyiyayaya123123** [comment]
是docker运行的

**Comment by hajiuhajiu** [comment]
进入控制面板， 打开定时任务，定时任务里加入下面一条，存盘

22 * * * * bash /root/jd/git_pull.sh >/dev/null 2>&1

前几天我操作失误， 重置了配置文件，导致定时任务失效
