### ISSUE TITLE
docker清除日志问题

### ISSUE THREAD

**Issue by greedisgoood** [hajiuhajiu/jdsign1112#36]
#!/bin/sh 
echo "======== start clean docker containers logs ========"  

logs=$(find /var/lib/docker/containers/ -name *-json.log)  

for log in $logs  
        do  
                echo "clean logs : $log"  
                cat /dev/null > $log  
        done  

echo "======== end clean docker containers logs ========"

清除容器日志不能使新cookie 生效，请问有没有方法，或者能不能把这个作为功能更新一下。
添麻烦了

**Comment by greedisgoood** [comment]
我似乎理解错了  每次更新cookie 是要删除/root/jd-docker/log。。这个文件吗？

**Comment by greedisgoood** [comment]
试了试，删除/root/jd-docker/log，会生效，但是过一会儿，又提示cookie失效了。我docker重新才好了

**Comment by hajiuhajiu** [comment]
你获取cookie的方法有问题吧，在浏览器里用f12可以看到cookie的有效期，你核对一下

**Comment by hajiuhajiu** [comment]
别人也反馈这个问题了,这边没法复现,先把cookie检查的文件替换掉看看
