### ISSUE TITLE
安装之后，容器一直重启，不知道为什么

### ISSUE THREAD

**Issue by zhwshok** [hajiuhajiu/jdsign1112#37]
![IMG_20220104_210815](https://user-images.githubusercontent.com/44687257/148071575-7d01006c-6bfd-4db4-8c3c-dcf2aadaf255.jpg)
![IMG_20220104_210751](https://user-images.githubusercontent.com/44687257/148071587-a7a674cb-37f2-4b0e-ba83-63ba2d98ba88.jpg)
帮忙看一下吧

**Comment by hajiuhajiu** [comment]
从你的描述看不出具体什么问题,我从头重新操作了一遍也没法复现你的问题,你可以安装portainer看看具体的运行日志, 就能看到哪一步出错了


docker pull portainer/portainer

docker run -d -p 9000:9000 -v /root/portainer:/data -v /var/run/docker.sock:/var/run/docker.sock --name dev-portainer portainer/portainer
