### ISSUE TITLE
yml少了很多

### ISSUE THREAD

**Issue by 357283670** [hajiuhajiu/jdsign1112#8]
刚同步了一下新更新的仓库，yml少了很多。是移除了失效的吗，还是要上新的呢？

**Comment by 357283670** [comment]
你的jd_daily_egg.js就忘了设置yml时间，不知道是遗忘了还是这个没什么用呢？

**Comment by hajiuhajiu** [comment]
添加了， 这个没啥收益 ，容易黑号。
最近活动不多
